### ISSUE TITLE
4_tokenization has 2 solution files and no exercise file

### ISSUE THREAD

**Issue by chelouche9** [codebasics/nlp-tutorials#1]
Hi, 

First I would like to state how I really enjoy your tutorials and find them VERY helpful!

In the tokenization lesson, both exercise files are the solution. Just to let you know :)

**Comment by dhavalsays** [comment]
Hey, @chelouche9 Thanks for your kind words of appreciation. I just checked, its all good because in the main tutorial file towards that end we have an exercise statement (I didn't create a separate exercise file) and then when you click on a solution link it takes you to a solution notebook.
